# Generated by Django 3.2.25 on 2025-11-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='PChome ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名稱')),
                ('pic_url', models.URLField(blank=True, max_length=512, null=True, verbose_name='圖片連結')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '電腦零件',
                'verbose_name_plural': '電腦零件列表',
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='價格')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='爬取時間')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='core.product')),
            ],
            options={
                'verbose_name': '價格紀錄',
                'verbose_name_plural': '價格紀錄表',
                'db_table': 'price_history',
                'ordering': ['-crawled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', 'crawled_at'], name='price_histo_product_826b0a_idx'),
        ),
    ]
