# Generated by Django 3.2.25 on 2025-11-23 11:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆ (1分)'), (2, '★★☆☆☆ (2分)'), (3, '★★★☆☆ (3分)'), (4, '★★★★☆ (4分)'), (5, '★★★★★ (5分)')], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='評分')),
                ('comment', models.TextField(blank=True, verbose_name='評論內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='評論時間')),
            ],
            options={
                'verbose_name': '商品評價',
                'verbose_name_plural': '商品評價列表',
                'db_table': 'product_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MB', '主機板'), ('CPU', '處理器'), ('RAM', '記憶體'), ('GPU', '顯示卡'), ('SSD', '硬碟'), ('OTHER', '其他')], default='OTHER', max_length=10, verbose_name='零件分類'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=dict, verbose_name='規格參數 (JSON)'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='crawled_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='爬取時間'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_name_6f9890_idx'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
    ]
