# Generated by Django 3.2.25 on 2026-08-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251123_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delisted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下架時間'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否仍在架上'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MB', '主機板'), ('CPU', '處理器'), ('RAM', '記憶體'), ('GPU', '顯示卡'), ('SSD', '固態硬碟'), ('HDD', '傳統硬碟'), ('PSU', '電源供應器'), ('CASE', '機殼'), ('OTHER', '其他')], default='OTHER', max_length=10, verbose_name='零件分類'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'),
        ),
    ]
